#!/bin/bash
#
# activemq       Starts ActiveMQ.
#
# chkconfig: 345 88 12
# description: ActiveMQ is a JMS Messaging Queue Server.
### BEGIN INIT INFO
# Provides: $activemq
### END INIT INFO

. /etc/init.d/functions

export JAVA_HOME=/usr
export KLOOPZ_AMQ_PASS=amqpass

start() {
       echo -n $"Starting ActiveMQ: "
       /opt/activemq/bin/linux-x86-64/activemq start
       echo
       return $RETVAL
}
stop() {
       echo -n $"Shutting down ActiveMQ: "
       /opt/activemq/bin/linux-x86-64/activemq stop
       echo
       return $RETVAL
}
restart() {
       stop
       start
}
case "$1" in
start)
       start
       ;;
stop)
       stop
       ;;
restart|reload)
       restart
       ;;
*)
       echo $"Usage: $0 {start|stop|restart}"
       exit 1
esac
 
exit $?
