#!/bin/bash

# Tomcat7: Start/Stop Tomcat 7
#
# chkconfig: - 90 10
# description: Tomcat is a Java application Server.

. /etc/init.d/functions
. /etc/sysconfig/network

CATALINA_HOME=/usr/local/tomcat7
TOMCAT_USER=tomcat7
TOMCAT_GROUP=tomcat7


LOCKFILE=/var/lock/subsys/tomcat7
export CATALINA_PID="/var/run/tomcat7.pid"

SHUTDOWN_WAIT=30
RETVAL=0
start(){
    echo "Starting Tomcat7: "
    
    touch $CATALINA_PID 2>&1 || RETVAL="4"
    if [ "$RETVAL" -eq "0" -a "$?" -eq "0" ]; then 
      chown ${TOMCAT_USER}:${TOMCAT_GROUP} $CATALINA_PID
    fi
    
    su - $TOMCAT_USER -c "$CATALINA_HOME/bin/startup.sh"
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCKFILE
    return $RETVAL
}

stop(){
     echo "Shutting down Tomcat7: "
     $CATALINA_HOME/bin/shutdown.sh
     RETVAL=$?
     echo $RETVAL
     count="0"
     if   [ "$RETVAL" -eq "4" ]; then
        echo "Tomcat stop could not be invoked(Potential tomcat too busy or does not respond to stop request ); killing tomcat process"
        SHUTDOWN_WAIT=0
     fi
     if [ -f "${CATALINA_PID}" ]; then
        read kpid < ${CATALINA_PID}
        until [ "$(ps --pid $kpid | grep -c $kpid)" -eq "0" ] || \
                  [ "$count" -gt "$SHUTDOWN_WAIT" ]; do
                echo "waiting for processes $kpid to exit"
                sleep 1
                let count="${count}+1"
        done
        if [ "$count" -gt "$SHUTDOWN_WAIT" ]; then
                echo  "killing processes which did not stop after ${SHUTDOWN_WAIT} seconds"
                kill -9 $kpid
        fi
     
	rm -f $CATALINA_PID
     fi
     rm -f $LOCKFILE

    #[ $RETVAL -eq 0 ] && rm -f $LOCKFILE
     return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
exit $?